{
 "title": "Speedtest",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download vs Upload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Mbits", "label": "Download in Mbps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(dl) AS \"Download\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(ul) AS \"Upload\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "ping in ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(ping) AS \"ping\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  { "title": "Single Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Letzer Download Test",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  dl\nFROM data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Letzer Upload Test",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ul\nFROM data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Minimal",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
     "format": "Mbits",
     "valueName": "min",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  min(dl) AS \"dl\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      }
     ]
    },
    {
     "title": "Download Maximal",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
     "format": "Mbits",
     "valueName": "max",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  max(dl) AS \"dl\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      }
     ]
    },
    {
     "title": "Upload Minimal",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
     "format": "Mbits",
     "valueName": "min",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  min(ul) AS \"dl\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      }
     ]
    },
    {
     "title": "Download Maximal",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
     "format": "Mbits",
     "valueName": "max",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  max(ul) AS \"dl\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(dl) AS \"Download\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(ul) AS \"Upload\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(ping) AS \"Ping\"\nFROM data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
      }
     ]
    }
   ]
  }
 ]
}